authnapp/urls.py
from django.urls import path, re_path

import authnapp.views as authnapp
# from authnapp.apps import AuthnappConfig

app_name = "authnapp"  # имя в уроке AuthapppConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    # path("login/", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    # path("logout/", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    # path("register/", authnapp.register, name="register"),
    re_path(r"^edit/$", authnapp.edit, name="edit"),
    # path("edit/", authnapp.edit, name="edit"),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authnapp.verify, name='verify'),
    re_path(r"^send_message/$", authnapp.send_message, name="send_message"),

    # re_path(r"^send_verify_mail/(?P<user>\w+)/$", authnapp.send_verify_mail, name="send_verify_mail"),

]

basketapp/urls.py
from django.urls import re_path

import basketapp.views as basketapp

from .apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    re_path(r"^$", basketapp.basket, name="view"),
    # path("", basketapp.basket, name="view"),
    re_path(r"^add/(?P<pk>\d+)/$", basketapp.basket_add, name="add"),
    # path("add/<int:pk>/", basketapp.basket_add, name="add"),
    re_path(r"^remove/(?P<pk>\d+)/$", basketapp.basket_remove, name="remove"),
    # path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
    re_path(r"^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$", basketapp.basket_edit, name="edit"),
    # path("edit/<int:pk>/<int:quantity>/", basketapp.basket_edit, name="edit"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import re_path, path

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    # path("", mainapp.main, name="main"),
    re_path(r"^products/", include("mainapp.urls", namespace="products")),
    # path("products/", include("mainapp.urls", namespace="products")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    # path("contact/", mainapp.contact, name="contact"),
    path("", include("social_django.urls", namespace="social")),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    # path("auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    # path("basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^order/", include("ordersapp.urls", namespace="order")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    # path("admin/", include("adminapp.urls", namespace="admin")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.products, name="index"),
    # path("", mainapp.products, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.products, name="category"),
    # path("category/<int:pk>/", mainapp.products, name="category"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.products, name="page"),
    # path("category/<int:pk>/page/<int:page>/", mainapp.products, name="page"),
    re_path(r"^product/(?P<pk>\d+)/$", mainapp.product, name="product"),
    # path("product/<int:pk>/", mainapp.product, name="product"),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name="категория активна", db_index=True, default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя продукта", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    short_desc = models.CharField(verbose_name="краткое описание продукта", max_length=60, blank=True)
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="количество на складе", default=0)
    is_active = models.BooleanField(verbose_name="продукт активен", db_index=True, default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by("category", "name")


class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Москва", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

mainapp/views.py
import random

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from django.views.decorators.cache import cache_page


from .models import Contact, Product, ProductCategory


def get_links_menu():
    if settings.LOW_CACHE:
        key = "links_menu"
        links_menu = cache.get(key)
        if links_menu is None:
            # print(f'caching {key}')
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f"category_{pk}"
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = "products"
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related("category")
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related("category")


def get_product(pk):
    if settings.LOW_CACHE:
        key = f"product_{pk}"
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = "products_orederd_by_price"
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by("price")
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by("price")


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f"products_in_category_orederd_by_price_{pk}"
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                "price"
            )
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by("price")


def main(request):
    title = "главная"
    products = get_products()[:3]
    content = {"title": title, "products": products, "media_url": settings.MEDIA_URL}
    return render(request, "mainapp/index.html", content)


# def get_hot_product():
#     products = Product.objects.filter(is_active=True, category__is_active=True)
#     return random.sample(list(products), 1)[0]


# def get_same_products(hot_product):
#     same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]
#     return same_products


# def get_same_products(hot_product):
#     same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]
#     return same_products




def get_hot_product_list():
    products = Product.objects.filter(is_active=True, category__is_active=True).select_related("category")
    hot_product = random.sample(list(products), 1)[0]
    hot_list = products.exclude(pk=hot_product.pk)[:3]
    return (hot_product, hot_list)


def products(request, pk=None, page=1):
    title = "продукты"
    links_menu = get_links_menu()

    if pk is not None:
        if str(pk) == str(0):
            category = {"pk": 0, "name": "все"}
            products = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            "title": title,
            "links_menu": links_menu,
            "category": category,
            "products": products_paginator,
            "media_url": settings.MEDIA_URL,
        }
        return render(request, "mainapp/products_list.html", content)
    # hot_product = get_hot_product()
    # same_products = get_same_products(hot_product)
    hot_product, same_products = get_hot_product_list()
    content = {
        "title": title,
        "links_menu": links_menu,
        "same_products": same_products,
        "media_url": settings.MEDIA_URL,
        "hot_product": hot_product,
    }
    return render(request, "mainapp/products.html", content)


def product(request, pk):
    title = "продукты"
    content = {
        "title": title,
        "links_menu": get_links_menu(),
        "product": get_product(pk),
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/product.html", content)


@cache_page(600)
def contact(request):
    title = "о нас"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contact.html", content)

mainapp/templates/mainapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|capfirst }}
        {% endblock title %}
    </title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    {% endblock css %}

    {% block js %}
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock js %}

</head>

<body>
    <div class="container">

        {% block menu %}
        {% endblock menu %}

        <div class="content">
            {% block content %}
            {% endblock content %}
        </div>

    </div>

    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}

</body>

</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles mail_to %}


{% block menu %}
<div class="hero">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <h1>наши контакты</h1>
    <p>сегодня: {{ visit_date|date:"l, j F, Y" }}</p>
</div>
{% endblock %}

{% block content %}
<div class="location">
    {% for location in locations %}
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>{{ location.city }}</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>{{ location.phone }}</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>{{ location.email|mail_to }}</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>{{ location.address }}</p>
        </div>
    </div>
    {% endfor %}
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
<div class="slider">
    <div class="header clearfix">
		{% include 'mainapp/includes/inc_menu.html' %}
	</div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">
            заказать
            <img src="{% static 'img/arrow.png' %}" alt="">
        </a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
{% endblock %}


{% block content %}
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="{{ product.image }}"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>Описание: {{ product.description }} </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{{ media_url }}{{ product.image }}" alt="вариант 1">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{{ media_url }}{{ product.image }}" alt="вариант 2">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{{ media_url }}{{ product.image }}" alt="вариант 3">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
            <br>
            <p class="price"> {{ product.price }} <span>руб</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать
                <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ product.description }}
            </div>
        </div>
    </div>
</div>
<div class="clr"></div>
{% endblock content %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_menu.html' %}
	</div>
</div>
{% endblock %}

{% block content %}
<div class="details">
	<div class="links clearfix">
		{% include 'mainapp/includes/inc_categories_menu.html' %}
	</div>

	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ media_url }}{{ hot_product.image }}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{{ media_url }}{{ hot_product.image }}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{{ media_url }}{{ hot_product.image }}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{{ media_url }}{{ hot_product.image }}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">{{ hot_product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price">{{ hot_product.price }} <span>руб</span></p>
			<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ hot_product.description }}
			</div>
		</div>
	</div>

	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
		</div>
		<div class="related-products clearfix">
			{% for product in same_products %}
			<div class="block">
				<a href="{% url 'products:product' product.pk %}"><img src="{{ media_url }}{{ product.image }}"
						alt="{{ product.short_desc }}">
					<div class="text">
						<img src="/static/img/icon-hover.png" alt="img">
						<h3>Категория:{{ product.category.name }}</h3>
						<h4>Название: {{ product.name }}</h4>
						<p>Описание: {{ product.description }} </p>
						<p>Цена: {{ product.price }} </p>
						<p>На складе: {{ product.quantity }} </p>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

<div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends "mainapp/products.html" %}
{% load staticfiles %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include "mainapp/includes/inc_categories_menu.html" %}
    </div>

    <div class="products_list">
        <div class="title clearfix">
            <h2>Категория: "{{ category.name|title }}"</h2>
            <div class="paginator">
                {% if products.has_previous %}
                <a href="{% url 'products:page' category.pk products.previous_page_number %}"><i
                        class="fas fa-chevron-circle-left"></i></a>
                {% endif %}
                <span class="current">
                    страница {{ products.number }} из {{ products.paginator.num_pages }}
                </span>
                {% if products.has_next %}
                <a href="{% url 'products:page' category.pk products.next_page_number %}"><i
                        class="fas fa-chevron-circle-right"></i></a>
                {% endif %}
            </div>
        </div>
        <div class="category-products clearfix">
            {% for product in products %}
            <div class="block">
                {% if user.is_authenticated %}
                <a href="{% url 'products:product' product.pk %}">
                    {% else %}
                    <a href="{% url 'auth:login' %}">
                        {% endif %}
                        <img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.description }} </p>
                        </div>
                    </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="clr"></div>

{% endblock %}