authnapp/urls.py
from django.urls import path, re_path

import authnapp.views as authnapp
# from authnapp.apps import AuthnappConfig

app_name = "authnapp"  # имя в уроке AuthapppConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    # path("login/", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    # path("logout/", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    # path("register/", authnapp.register, name="register"),
    re_path(r"^edit/$", authnapp.edit, name="edit"),
    # path("edit/", authnapp.edit, name="edit"),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authnapp.verify, name='verify'),
    re_path(r"^send_message/$", authnapp.send_message, name="send_message"),

    # re_path(r"^send_verify_mail/(?P<user>\w+)/$", authnapp.send_verify_mail, name="send_verify_mail"),

]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import re_path, path

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    # path("", mainapp.main, name="main"),
    re_path(r"^products/", include("mainapp.urls", namespace="products")),
    # path("products/", include("mainapp.urls", namespace="products")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    # path("contact/", mainapp.contact, name="contact"),
    path("", include("social_django.urls", namespace="social")),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    # path("auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    # path("basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^order/", include("ordersapp.urls", namespace="order")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    # path("admin/", include("adminapp.urls", namespace="admin")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.products, name="index"),
    # path("", mainapp.products, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.products, name="category"),
    # path("category/<int:pk>/", mainapp.products, name="category"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.products, name="page"),
    # path("category/<int:pk>/page/<int:page>/", mainapp.products, name="page"),
    re_path(r"^product/(?P<pk>\d+)/$", mainapp.product, name="product"),
    # path("product/<int:pk>/", mainapp.product, name="product"),
]

authnapp/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to="users_avatars", blank=True)
    age = models.PositiveIntegerField(verbose_name="возраст", default=18)
    activation_key = models.CharField(verbose_name="ключ подтверждения", max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(
        verbose_name="актуальность ключа", default=(now() + timedelta(hours=48))
    )

    def is_activation_key_expired(self):
        if now() <= self.activation_key_expires:
            return False
        else:
            return True


class ShopUserProfile(models.Model):
    MALE = "M"
    FEMALE = "W"

    GENDER_CHOICES = (
        (MALE, "М"),
        (FEMALE, "Ж"),
    )

    user = models.OneToOneField(ShopUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    tagline = models.CharField(verbose_name="теги", max_length=128, blank=True)
    aboutMe = models.TextField(verbose_name="о себе", max_length=512, blank=True)
    gender = models.CharField(verbose_name="пол", max_length=1, choices=GENDER_CHOICES, blank=True)

    @receiver(post_save, sender=ShopUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            ShopUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=ShopUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.shopuserprofile.save()

authnapp/forms.py
import hashlib
import random

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm

from .models import ShopUser, ShopUserProfile


class ShopUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = ShopUser
        fields = ("username", "password")


class ShopUserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    def clean_age(self):
        data = self.cleaned_data["age"]
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data

    def save(self):
        user = super(ShopUserRegisterForm, self).save()

        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user

    class Meta:
        model = ShopUser
        fields = ("username", "first_name", "password1", "password2", "email", "age", "avatar")


class ShopUserEditForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    def clean_age(self):
        data = self.cleaned_data["age"]
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

    class Meta:
        model = ShopUser
        fields = ("username", "first_name", "email", "age", "avatar")


class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        fields = ("tagline", "aboutMe", "gender")

    def __init__(self, *args, **kwargs):
        super(ShopUserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

authnapp/views.py
from django.conf import settings
from django.contrib import auth
from django.core.mail import send_mail
from django.db import transaction
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from authnapp.forms import ShopUserEditForm, ShopUserLoginForm, ShopUserRegisterForm, ShopUserProfileEditForm
from authnapp.models import ShopUser


def login(request):
    title = "вход"

    login_form = ShopUserLoginForm(data=request.POST or None)
    next_page = request.GET["next"] if "next" in request.GET.keys() else ""

    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if "next_page" in request.POST.keys():
                return HttpResponseRedirect(request.POST["next_page"])
            return HttpResponseRedirect(reverse("main"))

    content = {"title": title, "login_form": login_form, "next_page": next_page}
    return render(request, "authnapp/login.html", content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main"))


def register(request):
    title = "регистрация"

    if request.method == "POST":
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_mail(user):
                print('Сообщение для потверждения регистрации отправлено')

                # return HttpResponseRedirect(reverse("auth:send_message", args=[user]))

                return HttpResponseRedirect(reverse("auth:send_message"))
    else:
        register_form = ShopUserRegisterForm()

    content = {"title": title, "register_form": register_form}
    return render(request, "authnapp/register.html", content)


def send_message(request):
    return render(request, "authnapp/send_message.html")


@login_required
@transaction.atomic
def edit(request):
    title = "редактирование"

    if request.method == "POST":
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("auth:edit"))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.shopuserprofile)

    content = {"title": title, "edit_form": edit_form, "profile_form": profile_form, "media_url": settings.MEDIA_URL}

    return render(request, "authnapp/edit.html", content)


def send_verify_mail(user):
    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])
    title = f'Потверждение учетной записи {user.username}'
    message = f'Для потверждения учетной записи {user.username} на портале {settings.DOMAIN_NAME}\
              \n перейдите по ссылке {settings.DOMAIN_NAME}{verify_link}'

    print(f'from: {settings.EMAIL_HOST_USER}, to: {user.email}')
    return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


def verify(request, email, activation_key):
    try:
        user = ShopUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            print(f'user {user} is activated')
            user.is_active = True
            user.save()
            auth.login(request, user, backend="django.contrib.auth.backends.ModelBackend")

            return render(request, 'authnapp/verification.html')
        # else:
        print(f'error activation user: {user}')
        return render(request, 'authnapp/verification.html')

    except Exception as e:
        print(f'error activation user: {e.args}')

    return HttpResponseRedirect(reverse('main'))

authnapp/templates/authnapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock js %}

</head>

<body>
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}
            {% endblock content %}

        </div>
    </div>
</body>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

</html>

authnapp/templates/authnapp/edit.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.as_p }}
    {{ profile_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
    <a href="{% url 'main' %}" class="">
        на главную
    </a>
</button>

{% if user.avatar %}
<div class="user_avatar"><img src="{{ media_url }}{{ user.avatar }}"></div>
{% endif %}

{% endblock %}

authnapp/templates/authnapp/login.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
    {% csrf_token %}
    {% if next_page %}
        <input type="hidden" name="next_page" value="{{ next_page }}">
    {% endif %}
    {{ login_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="войти">
</form>
<a href="{% url 'auth:register' %}" class="btn btn-outline-secondary btn-block" role="button">
    зарегистрироваться
</a>
<a href="{% url 'social:begin' 'vk-oauth2' %}?next=/" class="btn btn-primary btn-block" role="button">
    Вход через <i class="fa fa-vk" aria-hidden="true"></i>
</a>
    <a href="{% url 'social:begin' 'github' %}?next=/" class="btn btn-primary btn-block" role="button">
    Вход через <i class="fab fa-github" aria-hidden="true"></i>
</a>



{% endblock content %}

authnapp/templates/authnapp/register.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ register_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="зарегистрироваться">
</form>

{% endblock %}

authnapp/templates/authnapp/send_message.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

 {% block js %}
    <script src="{% static 'js/mytimer.js' %}"></script>

 {% endblock %}



{% block content %}
    <h3>Сообщение для потверждения регистрации отправлено</h3>
<br>
<button class="btn btn-round form-control">
    <a href="{% url 'auth:login' %}" class="">
        Ok
    </a>
</button>


{#<button class="btn btn-round form-control">#}
{#    {{ user.pk }}#}
{#    <a href="{% url 'auth:send_verify_mail' user.pk %}" class="">#}
{#        отправить повторно#}
{#    </a>#}
{#</button>#}


{% endblock %}

authnapp/templates/authnapp/verification.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}


{% block content %}
{% if user %}
<h3>Поздравляем!</h3>
<br>
<h4>Пользователь {{user.username}} подтвержден.</h4>
{% else %}
<h3>Верификация не пройдена.</h3>
{% endif %}
<br>
<button class="btn btn-round form-control">
    <a href="{% url 'main' %}" class="">
        на главную
    </a>
</button>

{% endblock %}