geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import re_path, path

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    # path("", mainapp.main, name="main"),
    re_path(r"^products/", include("mainapp.urls", namespace="products")),
    # path("products/", include("mainapp.urls", namespace="products")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    # path("contact/", mainapp.contact, name="contact"),
    path("", include("social_django.urls", namespace="social")),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    # path("auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    # path("basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^order/", include("ordersapp.urls", namespace="order")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    # path("admin/", include("adminapp.urls", namespace="admin")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.products, name="index"),
    # path("", mainapp.products, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.products, name="category"),
    # path("category/<int:pk>/", mainapp.products, name="category"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.products, name="page"),
    # path("category/<int:pk>/page/<int:page>/", mainapp.products, name="page"),
    re_path(r"^product/(?P<pk>\d+)/$", mainapp.product, name="product"),
    # path("product/<int:pk>/", mainapp.product, name="product"),
]

ordersapp/urls.py
from django.urls import re_path

import ordersapp.views as ordersapp
from ordersapp.apps import OrdersappConfig

app_name = OrdersappConfig.name

urlpatterns = [
    re_path(r"^$", ordersapp.OrderList.as_view(), name="orders_list"),
    re_path(r"^create/$", ordersapp.OrderItemsCreate.as_view(), name="order_create"),
    re_path(r"^read/(?P<pk>\d+)/$", ordersapp.OrderRead.as_view(), name="order_read"),
    re_path(r"^update/(?P<pk>\d+)/$", ordersapp.OrderItemsUpdate.as_view(), name="order_update"),
    re_path(r"^delete/(?P<pk>\d+)/$", ordersapp.OrderDelete.as_view(), name="order_delete"),
    re_path(r"^forming/complete/(?P<pk>\d+)/$", ordersapp.order_forming_complete, name="order_forming_complete"),
    re_path(r"^product/(?P<pk>\d+)/price/$", ordersapp.get_product_price),
]

ordersapp/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import get_object_or_404

from mainapp.models import Product


class Order(models.Model):
    FORMING = "FM"
    SENT_TO_PROCEED = "STP"
    PROCEEDED = "PRD"
    PAID = "PD"
    READY = "RDY"
    CANCEL = "CNC"

    ORDER_STATUS_CHOICES = (
        (FORMING, "формируется"),
        (SENT_TO_PROCEED, "отправлен в обработку"),
        (PAID, "оплачен"),
        (PROCEEDED, "обрабатывается"),
        (READY, "готов к выдаче"),
        (CANCEL, "отменен"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name="создан", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="обновлен", auto_now=True)
    status = models.CharField(verbose_name="статус", max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name="активен", db_index=True, default=True)

    class Meta:
        ordering = ("-created",)
        verbose_name = "заказ"
        verbose_name_plural = "заказы"

    def __str__(self):
        return "Текущий заказ: {}".format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name="продукт", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="количество", default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return get_object_or_404(OrderItem, pk=pk)

    # # Object's saving method
    # def save(self, *args, **kwargs):
    #     if self.pk:
    #         self.product.quantity -= self.quantity - self.__class__.get_item(self.pk).quantity
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super(self.__class__, self).save(*args, **kwargs)
    #
    # # Object's deleting method
    # def delete(self):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(self.__class__, self).delete()

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Order
        exclude = ("user",)


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label="цена", required=False)

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        # self.fields["product"].queryset = Product.get_items()
        super(OrderItemForm, self).__init__(*args, **kwargs)
        self.fields["product"].queryset = Product.get_items().select_related()
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = OrderItem
        exclude = ()

ordersapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


class OrderList(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy("ordersapp:orders_list")

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = self.request.user.basket.select_related().order_by("product__category")
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial["product"] = basket_items[num].product
                    form.initial["quantity"] = basket_items[num].quantity
                    form.initial["price"] = basket_items[num].product.price
            else:
                formset = OrderFormSet()

        data["orderitems"] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context["orderitems"]

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
            # Delete items in basket after order creating only
            Basket.objects.filter(user=self.request.user).delete()

        # Delete empty order
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context["title"] = "заказ/просмотр"
        return context


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy("ordersapp:orders_list")

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            data["orderitems"] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)

            # formset = OrderFormSet(instance=self.object)

            for form in formset.forms:
                if form.instance.pk:
                    form.initial["price"] = form.instance.product.price
            data["orderitems"] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context["orderitems"]

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # Delete empty order
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy("ordersapp:orders_list")


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse("ordersapp:orders_list"))


from django.db.models import F


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(instance, sender, **kwargs):
    if instance.pk:
        instance.product.quantity = F("quantity") - (instance.quantity - sender.get_item(instance.pk).quantity)
    else:
        instance.product.quantity = F("quantity") - instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(instance, **kwargs):
    instance.product.quantity = F("quantity") + instance.quantity
    instance.product.save()


from django.http import JsonResponse

from mainapp.models import Product


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({"price": product.price})
        else:
            return JsonResponse({"price": 0})

ordersapp/templates/ordersapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ "Кабинет заказов"|title }}
        {% endblock %}
    </title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}">
    {% endblock css %}

</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

{% block js %}
<!-- Bootstrap section -->
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
    // Enable tooltips everywhere
    //   https://getbootstrap.com/docs/4.4/components/tooltips/#example-enable-tooltips-everywhere
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
<!-- jQuery formset section -->
<script src="{% static 'js/jquery.formset.js' %}"></script>
<!-- GeekShop section -->
<script src="{% static 'js/orders_scripts.js' %}"></script>
{% endblock js %}

</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
{{ var }}
<p>
<h3>Вы уверены, что хотите удалить данный заказ?</h3>
</p>
<p>
<form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
    {% csrf_token %}
    <div class="btn-group col-12" role="group">
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-outline-secondary"
            role="button">{{ "отмена"|capfirst }}</a>
        <button type="submit" class="btn btn-outline-danger">{{ "удалить"|capfirst }}</button>
    </div>
</form>
</p>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load staticfiles %}

{% block content %}

{% include 'ordersapp/includes/inc_order_summary.html' %}
<p>
<h3>
    Товары заказа
</h3>
</p>
<p>
<table class="table">
    <thead>
        <tr>
            <th scope="col" class="col-4">Изображение</th>
            <th scope="col" class="col-8">Описание</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object.orderitems.select_related %}
        <tr>
            <td>
                <img src="{{ MEDIA_URL }}{{ item.product.image }}" alt="{{ item.product.short_desc }}"
                    style="min-width: 250px; max-width: 250px;">
            </td>
            <td>
                <span class="category_name">{{ item.product.category.name }}</span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">{{ item.product.price }}&nbspруб</span>
                <span class="product_quantitiy">x {{ item.quantity }} шт.</span>
                <span class="product_cost"> = {{ item.get_product_cost }}&nbspруб</span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</p>
<p>
<div class="btn-group col-12" role="group">
    {% include 'ordersapp/includes/inc_order_actions.html' %}
</div>
</p>

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load staticfiles cache %}

{% block content %}

{% include 'ordersapp/includes/inc_order_summary.html' %}
<p>
<h3>
    {% if view.object %}
    Редактирование товаров заказа
    {% else %}
    Создание нового заказа
    {% endif %}
    {{ var }}
</h3>
</p>
<p>
<div class="order_form">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <table class="table">
            {{ orderitems.management_form }}
            {% for form in orderitems.forms %}
            {% if forloop.first %}
            <thead>
                <tr>
                    {% for field in form.visible_fields %}
                    <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                        {{ field.label|capfirst }}
                    </th>
                    {% endfor %}
                </tr>
            </thead>
            {% endif %}
            <tr class="formset_row">
                {% for field in form.visible_fields %}
                <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {% if field.name != 'price' %}
                        {{ field }}
                    {% else %}
                        {% if field.value %}
                            <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">{{ field.value }}</span> руб
                        {% endif %}
                    {% endif %}
                </td>

                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <p>
        <div class="btn-group col-12" role="group">
            <button type="submit" value="сохранить" class="btn btn-outline-secondary">сохранить</button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </div>
        </p>
    </form>
</div>
</p>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}


{% block content %}
<p class="h2 text-center">
    Ваши заказы, уважаемый
    {% if user.first_name %}{{ user.first_name|title }}{% else %}{{ "пользователь"|capfirst }}{% endif %}
</p>
<p>
<div class="row justify-content-between">
    <div class="col-2">
        <a href="{% url 'main' %}" class="btn btn-sm btn-outline-secondary col-12" role="button"><i
                class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> {{ "на главную"|capfirst }}</a>
    </div>
    <div class="col-2">
        <a href="{% url 'ordersapp:order_create' %}" class="btn btn-sm btn-outline-success col-12" role="button"><i
                class="fa fa-plus" aria-hidden="true"></i> {{ "новый заказ"|capfirst }}</a>
    </div>
</div>
</p>
<p>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
            <th colspan="3">Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        {% if item.is_active %}
        <tr>
            <th scope="row">{{ item.pk }}</th>
            <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
            <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
            <td>{{ item.get_status_display }}</td>
            <td><a href="{% url 'ordersapp:order_read' item.pk %}" data-toggle="tooltip" data-placement="top"
                    title="Просмотр деталей"><i class="fa fa-list-alt" aria-hidden="true"></i></a></td>
            <td>
                {% if item.status == 'FM' %}
                <a href="{% url 'ordersapp:order_update' item.pk %}" data-toggle="tooltip" data-placement="top"
                    title="Редактировать"><i class=" fa fa-pencil" aria-hidden="true"></i></a>
                {% endif %}
            </td>
            <td>
                {% if item.status == 'FM' %}
                <a href="{% url 'ordersapp:order_delete' item.pk %}" data-toggle="tooltip" data-placement="top"
                    title="Удалить"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
</p>
{% endblock content %}